import { useEffect, useState } from 'react'
import Head from 'next/head';
import { Configuration, OpenAIApi } from "openai";
import { saveAs } from "file-saver";




export default function Home() {
  const [transparentActive, setTransparentActive] = useState(false);
  const [whiteActive, setWhiteActive] = useState(false);
  const [greyActive, setGreyActive] = useState(false);
  const [blackACtive, setBlackActive] = useState(false);
  const [backgroundColor, setBackgroundColor] = useState('');

  const [errorMessage, setErrorMessage] = useState(false);
  const [inputValue, setInputValue] = useState('');
  const [outputResults, setOutputResults] = useState(false);
  const [downloadAsset, setDownloadAsset] = useState(null);

  const API_KEY = process.env.OPEN_API_KEY

  // require('dotenv').config()
  useEffect(() => {
    console.log('hello');
    console.log("API_KEY", API_KEY)
  }, []);
  

  const handleRadioSelect = (e:any) => {
    console.log(e);
    // provide active class to item, so user knows its been selected 
    if (e.target.checked) {
      // console.log(e.target.value)
      // console.log(e.target.parentElement)

      if (e.target.value === 'transparent') {
        setTransparentActive(true);
        setWhiteActive(false);
        setGreyActive(false);
        setBlackActive(false);
        setBackgroundColor('border-dashed border-2 border-gray-500');
      } else if (e.target.value === 'white') {
        setTransparentActive(false);
        setWhiteActive(true);
        setGreyActive(false);
        setBlackActive(false);
        setBackgroundColor('bg-white');
      } else if (e.target.value === 'grey') {
        setTransparentActive(false);
        setWhiteActive(false);
        setGreyActive(true);
        setBlackActive(false);
        setBackgroundColor('bg-gray-200');
      } else if (e.target.value === 'black') {
        setTransparentActive(false);
        setWhiteActive(false);
        setGreyActive(false);
        setBlackActive(true);
        setBackgroundColor('bg-black');
      }
    }
  }

  const handleGenerateIcon = (e:any) => {
    e.preventDefault();
    console.log(inputValue)
    if (inputValue === '') {
      setErrorMessage(true)
      setOutputResults(false)
      return;
    }
    setOutputResults(true)
    setErrorMessage(false)
  }

  const handleDownload = (e:any) => {
    e.preventDefault();
    console.log('download');
  }

  const saveFile = (e:any) => {
    e.preventDefault();
    saveAs(
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "example.pdf"
    );
  };
  

  return (
    <>
      <Head>
        <title>OpenAI Icon Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <form action="/send-data-here" method="post" className="flex flex-col items-center">
          <div className="container flex justify-center items-center">
            <span className="text-5xl">Welcome to</span>
            <span className="ml-3 text-5xl">AIcon</span>
          </div>
          <div className="container flex justify-center items-center mt-6">
            <span className="text-2xl">
              Create your very own custom AI generated icons
            </span>
          </div>

          <div className="container flex justify-center items-center mt-6">
            <span className="text-3xl mr-4">I would like an icon of a </span>
            <input 
            className="text-2xl"
            type="text" 
            id="prompt" 
            placeholder="smiley face" 
            onChange={(event) =>
              setInputValue(event.target.value)
            }
            />
          </div>

           <div className="container flex justify-center items-center mt-6">
            <span className="text-2xl">Select background color: </span>

            <div className="grid grid-col-4 grid-flow-col gap-4 ml-6">
              <div className='flex flex-col items-center'>
                <label htmlFor="transparent" className={`flex w-16 h-16 rounded-lg border-dashed border-2 border-gray-500 cursor-pointer ${transparentActive ? "active" : ""}`} onClick={handleRadioSelect}>
                  <input className="hidden pointer" type="radio" id="transparent" name="transparent" value="transparent" />
                </label>
                 Transparent
              </div>

              <div className='flex flex-col items-center'>
                <label htmlFor="white" className={`flex w-16 h-16 border rounded-lg cursor-pointer ${whiteActive ? "active" : ""}`} onClick={handleRadioSelect}>
                  <input className="hidden pointer" type="radio" id="white" name="white" value="white" />
                </label>
                 White
              </div>

              <div className='flex flex-col items-center'>
                <label htmlFor="grey" className={`flex w-16 h-16 border rounded-lg bg-gray-200 cursor-pointer ${greyActive ? "active" : ""}`} onClick={handleRadioSelect}>
                  <input className="hidden pointer" type="radio" id="grey" name="grey" value="grey" />
                </label>
                 Grey
              </div>

              <div className='flex flex-col items-center'>
                <label htmlFor="black" className={`flex w-16 h-16 border rounded-lg bg-black cursor-pointer ${blackACtive ? "active" : ""}`} onClick={handleRadioSelect}>
                  <input className="hidden pointer" type="radio" id="black" name="black" value="black" />
                </label>
                 Black
              </div>

             
            </div>
          </div>
          <button 
          className='mt-12 rounded-lg bg-blue-500 text-white p-4 h-auto' 
          type="submit" 
          onClick={handleGenerateIcon}
          >
            Generate
          </button>

          {errorMessage && 
            <div className="text-red-500 mt-6">Please enter some text</div>
          }

          {outputResults && 
          <>
            <div className={`mt-12 results-container container rounded-lg flex justify-center items-center w-16 h-16 ${backgroundColor}`}>
              <img 
              className="w-9/12"
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" 
              alt="icon" />
            </div>
            <button 
            className="mt-6 bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center" 
            onClick={saveFile}
            >
              <svg className="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg>
              <span>Download</span>
            </button>
          </>
       
          }
        </form>
      </main>
    </>
  )
}
